/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'doctorId' : [] | [bigint],
  'serviceType' : string,
  'contactInfo' : string,
  'preferredDate' : Time,
  'patientName' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type ClinicStatus = { 'closed' : null } |
  { 'emergency' : null } |
  { 'open' : null };
export interface Doctor {
  'id' : bigint,
  'name' : string,
  'specialty' : string,
  'availability' : Array<DoctorAvailability>,
}
export interface DoctorAvailability {
  'doctorId' : bigint,
  'availableSlots' : Array<Time>,
}
export type ExternalBlob = Uint8Array;
export interface Review {
  'id' : bigint,
  'beforeAfterImage' : [] | [ExternalBlob],
  'text' : string,
  'reviewerName' : string,
  'state' : ReviewState,
  'rating' : bigint,
  'photo' : [] | [ExternalBlob],
}
export interface ReviewInput {
  'beforeAfterImage' : [] | [ExternalBlob],
  'text' : string,
  'reviewerName' : string,
  'rating' : bigint,
  'photo' : [] | [ExternalBlob],
}
export type ReviewState = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Service {
  'id' : string,
  'displayName' : string,
  'featuredPhoto' : [] | [ExternalBlob],
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addDoctor' : ActorMethod<
    [string, string, Array<DoctorAvailability>],
    bigint
  >,
  'addOrUpdateService' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'addReview' : ActorMethod<[ReviewInput], undefined>,
  'approveReview' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<
    [string, string, Time, string],
    Appointment
  >,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getApprovedReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinicStatus' : ActorMethod<[], ClinicStatus>,
  'getDoctorAvailability' : ActorMethod<
    [bigint],
    [] | [Array<DoctorAvailability>]
  >,
  'getPendingReviews' : ActorMethod<[], Array<Review>>,
  'getService' : ActorMethod<[string], [] | [Service]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectReview' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setClinicStatus' : ActorMethod<[ClinicStatus], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];