/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const DoctorAvailability = IDL.Record({
  'doctorId' : IDL.Nat,
  'availableSlots' : IDL.Vec(Time),
});
export const ReviewInput = IDL.Record({
  'beforeAfterImage' : IDL.Opt(ExternalBlob),
  'text' : IDL.Text,
  'reviewerName' : IDL.Text,
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Opt(IDL.Nat),
  'serviceType' : IDL.Text,
  'contactInfo' : IDL.Text,
  'preferredDate' : Time,
  'patientName' : IDL.Text,
});
export const BeforeAfterPair = IDL.Record({
  'id' : IDL.Nat,
  'afterImage' : ExternalBlob,
  'beforeImage' : ExternalBlob,
  'description' : IDL.Text,
});
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'availability' : IDL.Vec(DoctorAvailability),
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'displayName' : IDL.Text,
  'featuredPhoto' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
});
export const ReviewState = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'beforeAfterImage' : IDL.Opt(ExternalBlob),
  'text' : IDL.Text,
  'reviewerName' : IDL.Text,
  'state' : ReviewState,
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ClinicStatus = IDL.Variant({
  'closed' : IDL.Null,
  'emergency' : IDL.Null,
  'open' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addBeforeAfterPair' : IDL.Func(
      [ExternalBlob, ExternalBlob, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addDoctor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(DoctorAvailability)],
      [IDL.Nat],
      [],
    ),
  'addOrUpdateService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'addReview' : IDL.Func([ReviewInput], [], []),
  'approveReview' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllBeforeAfterPairs' : IDL.Func(
      [],
      [IDL.Vec(BeforeAfterPair)],
      ['query'],
    ),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinicStatus' : IDL.Func([], [ClinicStatus], ['query']),
  'getDoctorAvailability' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(DoctorAvailability))],
      ['query'],
    ),
  'getPendingReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getService' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setClinicStatus' : IDL.Func([IDL.Principal, ClinicStatus], [], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const DoctorAvailability = IDL.Record({
    'doctorId' : IDL.Nat,
    'availableSlots' : IDL.Vec(Time),
  });
  const ReviewInput = IDL.Record({
    'beforeAfterImage' : IDL.Opt(ExternalBlob),
    'text' : IDL.Text,
    'reviewerName' : IDL.Text,
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Opt(IDL.Nat),
    'serviceType' : IDL.Text,
    'contactInfo' : IDL.Text,
    'preferredDate' : Time,
    'patientName' : IDL.Text,
  });
  const BeforeAfterPair = IDL.Record({
    'id' : IDL.Nat,
    'afterImage' : ExternalBlob,
    'beforeImage' : ExternalBlob,
    'description' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'availability' : IDL.Vec(DoctorAvailability),
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'displayName' : IDL.Text,
    'featuredPhoto' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
  });
  const ReviewState = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'beforeAfterImage' : IDL.Opt(ExternalBlob),
    'text' : IDL.Text,
    'reviewerName' : IDL.Text,
    'state' : ReviewState,
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ClinicStatus = IDL.Variant({
    'closed' : IDL.Null,
    'emergency' : IDL.Null,
    'open' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addBeforeAfterPair' : IDL.Func(
        [ExternalBlob, ExternalBlob, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addDoctor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(DoctorAvailability)],
        [IDL.Nat],
        [],
      ),
    'addOrUpdateService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'addReview' : IDL.Func([ReviewInput], [], []),
    'approveReview' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllBeforeAfterPairs' : IDL.Func(
        [],
        [IDL.Vec(BeforeAfterPair)],
        ['query'],
      ),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinicStatus' : IDL.Func([], [ClinicStatus], ['query']),
    'getDoctorAvailability' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(DoctorAvailability))],
        ['query'],
      ),
    'getPendingReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getService' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setClinicStatus' : IDL.Func([IDL.Principal, ClinicStatus], [], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };